# -*- coding: utf-8 -*-
"""Fine Tuning Smoke Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-sf1Tjyx6mUJpKHYtGORewS7a38H_Xs
"""

# Commented out IPython magic to ensure Python compatibility.
# =========================
# BLOCK 1: clone + install + start API (fixed)
# =========================

from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import os
import time
import shutil
import subprocess
from pathlib import Path

# force a valid cwd
os.chdir("/content")
print("cwd:", os.getcwd())

REPO_URL = "https://github.com/AngshulMajumdar/Fine-tuned-mini-LLM-for-recommender-system.git"
REPO_DIR = Path("/content/Fine-tuned-mini-LLM-for-recommender-system")

if REPO_DIR.exists():
    shutil.rmtree(REPO_DIR)

!git clone "https://github.com/AngshulMajumdar/Fine-tuned-mini-LLM-for-recommender-system.git" /content/Fine-tuned-mini-LLM-for-recommender-system

assert REPO_DIR.exists(), f"Repo not cloned: {REPO_DIR}"
assert (REPO_DIR / "app" / "main.py").exists(), "Missing app/main.py"
assert (REPO_DIR / "requirements.txt").exists(), "Missing requirements.txt"

# %cd /content/Fine-tuned-mini-LLM-for-recommender-system
!pip -q install -r requirements.txt

server_log = "/content/movielens_ft_api_server.log"
if os.path.exists(server_log):
    os.remove(server_log)

proc = subprocess.Popen(
    ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"],
    cwd="/content/Fine-tuned-mini-LLM-for-recommender-system",
    stdout=open(server_log, "w"),
    stderr=subprocess.STDOUT,
)

print("Started PID:", proc.pid)

import requests

ok = False
for _ in range(60):
    try:
        r = requests.get("http://127.0.0.1:8000/health", timeout=5)
        if r.status_code == 200:
            print("HEALTH:", r.json())
            ok = True
            break
    except Exception:
        pass
    time.sleep(1)

if not ok:
    print(open(server_log).read())
    raise RuntimeError("Server did not start.")

# =========================
# BLOCK 1.5: simplify API output
# =========================

from pathlib import Path
import re
import os
import subprocess
import time
import requests

repo_main = Path("/content/Fine-tuned-mini-LLM-for-recommender-system/app/main.py")
assert repo_main.exists(), f"Missing file: {repo_main}"

new_score_pair = '''def score_pair(user_id: int, item_id: int):
    df, tokenizer, model, zero_id, one_id = load_assets()

    rows = df[(df["user_id"] == user_id) & (df["item_id"] == item_id)]
    if len(rows) == 0:
        raise HTTPException(status_code=404, detail="Pair not found in prepared test set.")

    row = rows.iloc[0].to_dict()
    prompt = build_prompt(row)

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=256)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits[0, -1]
        pair_logits = torch.stack([logits[zero_id], logits[one_id]])
        probs = torch.softmax(pair_logits, dim=0)

    score_1 = float(probs[1].item())
    pred = int(score_1 >= 0.5)

    return {
        "user_id": user_id,
        "item_id": item_id,
        "recommended": pred
    }
'''

text = repo_main.read_text(encoding="utf-8")
pattern = r"def score_pair\(user_id: int, item_id: int\):.*?@app\.get\(\"/health\"\)"
replacement = new_score_pair + '\n\n@app.get("/health")'
new_text, n = re.subn(pattern, replacement, text, flags=re.DOTALL)
assert n == 1, "Could not replace score_pair function cleanly."

repo_main.write_text(new_text, encoding="utf-8")
print("Updated:", repo_main)

!pkill -f "uvicorn app.main:app" || true
time.sleep(2)

server_log = "/content/movielens_ft_api_server.log"
if os.path.exists(server_log):
    os.remove(server_log)

proc = subprocess.Popen(
    ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"],
    cwd="/content/Fine-tuned-mini-LLM-for-recommender-system",
    stdout=open(server_log, "w"),
    stderr=subprocess.STDOUT,
)

print("Restarted PID:", proc.pid)

ok = False
for _ in range(60):
    try:
        r = requests.get("http://127.0.0.1:8000/health", timeout=5)
        if r.status_code == 200:
            print("HEALTH:", r.json())
            ok = True
            break
    except Exception:
        pass
    time.sleep(1)

if not ok:
    print(open(server_log).read())
    raise RuntimeError("Server did not restart.")

# =========================
# BLOCK 2: smoke test with real test-set pairs
# =========================

import pandas as pd
import requests

TEST_CSV = "/content/drive/MyDrive/movielens_100k_ft_distilgpt2_steps300_clean/prepared/test_examples.csv"
df = pd.read_csv(TEST_CSV)

row = df.iloc[0]
payload = {
    "user_id": int(row["user_id"]),
    "item_id": int(row["item_id"])
}

resp = requests.post("http://127.0.0.1:8000/predict", json=payload, timeout=60)
print("Single predict status:", resp.status_code)
print(resp.json())

batch_df = df.head(5)
batch_payload = {
    "pairs": [
        {"user_id": int(r["user_id"]), "item_id": int(r["item_id"])}
        for _, r in batch_df.iterrows()
    ]
}

resp2 = requests.post("http://127.0.0.1:8000/predict_batch", json=batch_payload, timeout=60)
print("Batch predict status:", resp2.status_code)
print(resp2.json())